#pragma once

#include "../../glconfig.h"

#if CUR_GL_TYPE == OPENGL_EGL
#include "GL/glew.h"
BEGIN_GFX_NAMESPACE
BEGIN_GL3_CORE_NAMESPACE

END_GL3_CORE_NAMESPACE
END_GFX_NAMESPACE

#endif  // CUR_GL_TYPE == OPENGL_EGL